### ISSUE TITLE
Plain PDF still have page breaks

### ISSUE THREAD

**Issue by PhilJbt** [iamgio/quarkdown#82]
As you can see from the last two PDF files attached in #81, plain PDFs always have page breaks. Did I miss something ?

__Version:__ *Development build 1.4.0*

**Comment by iamgio** [comment]
@PhilJbt are you sure you downloaded the [devbuild](https://github.com/iamgio/quarkdown/releases/tag/latest) instead of the stable release?

**Comment by iamgio** [comment]
Either you downloaded 1.4.0 by accident or you downloaded the devbuild before the CI finished uploading the artifacts. The white border in your plain PDFs was also fixed in the latest devbuild. Can you confirm?

**Comment by PhilJbt** [comment]
@iamgio I am sure. When I saw this bug, I re-downloaded the dev build, thinking I'd made a mistake. But it didn't change a thing.

EDIT: I tried again (downloading current dev build), and still have this issue with it.

**Comment by iamgio** [comment]
I managed to reproduce. I'm going to fix it.

**Comment by iamgio** [comment]
@PhilJbt it should be fixed in the latest devbuild. Let me know

**Comment by PhilJbt** [comment]
@iamgio This issue is also now fixed. Thank you for your promptness!
